spring.application.name=notification

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=notification
spring.datasource.password=notification
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Virtual Thread
spring.threads.virtual.enabled=true
